# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Tests for Delegation Tokens using test vectors.

Validates the implementation against vectors generated by
generate_delegation_tokens.py, which uses an independent reference
implementation (reference_schnorr48.py).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import cbor2
import pytest

from lichen.crypto.delegation_tokens import (
    COSE_ALG_LABEL,
    SCHNORR48_ED25519_ALG,
    DelegationScope,
    DelegationToken,
    DelegationTokenPayload,
    _build_sig_structure,
    _encode_protected_header,
)
from lichen.crypto.schnorr48 import verify

# Load test vectors
VECTORS_PATH = Path(__file__).parents[3] / "test" / "vectors" / "delegation_tokens.json"
with open(VECTORS_PATH) as f:
    VECTORS_DATA = json.load(f)


def get_vectors() -> list[dict[str, Any]]:
    """Get all test vectors."""
    return VECTORS_DATA["vectors"]


def get_vector(name: str) -> dict[str, Any]:
    """Get a single test vector by name."""
    matches = [v for v in VECTORS_DATA["vectors"] if v.get("name") == name]
    assert len(matches) == 1, f"Expected exactly one vector named {name!r}"
    return matches[0]


class TestVectorFormat:
    """Verify vector file format and constants."""

    def test_format_version(self) -> None:
        """Vectors use expected format version."""
        assert VECTORS_DATA["format_version"] == 1

    def test_algorithm_constant(self) -> None:
        """Vector algorithm ID matches implementation."""
        assert VECTORS_DATA["constants"]["algorithm"]["id"] == SCHNORR48_ED25519_ALG
        assert VECTORS_DATA["constants"]["algorithm"]["signature_length"] == 48


class TestProtectedHeader:
    """Verify protected header encoding matches vectors."""

    @pytest.mark.parametrize("vector", get_vectors(), ids=lambda v: v["name"])
    def test_protected_header(self, vector: dict[str, Any]) -> None:
        """Protected header encodes algorithm correctly."""
        protected = _encode_protected_header()
        assert protected.hex() == vector["protected_header"]

        # Verify decoded form
        decoded = cbor2.loads(protected)
        assert decoded[COSE_ALG_LABEL] == SCHNORR48_ED25519_ALG


class TestPayloadEncoding:
    """Verify payload CBOR encoding matches vectors."""

    @pytest.mark.parametrize(
        "vector",
        [
            v for v in get_vectors()
            if v.get("coverage") == "delegation_token_cose_sign1"
            and v.get("expected", {}).get("scope_bits_valid", True)
        ],
        ids=lambda v: v["name"],
    )
    def test_payload_cbor(self, vector: dict[str, Any]) -> None:
        """Payload CBOR encoding matches vector."""
        delegate = bytes.fromhex(vector["delegate_iid"])
        payload = DelegationTokenPayload(
            delegate=delegate,
            scope=vector["scope"],
            resource=vector["resource"],
            expiry=vector["expiry"],
            seq=vector["seq"],
        )
        assert payload.to_cbor().hex() == vector["payload_cbor"]


class TestSigStructure:
    """Verify Sig_structure construction per RFC 9052."""

    @pytest.mark.parametrize(
        "vector",
        [v for v in get_vectors() if "sig_structure_layout" in v],
        ids=lambda v: v["name"],
    )
    def test_sig_structure(self, vector: dict[str, Any]) -> None:
        """Sig_structure matches RFC 9052 encoding."""
        protected = bytes.fromhex(vector["protected_header"])
        payload = bytes.fromhex(vector["payload_cbor"])
        sig_structure = _build_sig_structure(protected, payload)
        assert sig_structure.hex() == vector["sig_structure"]

        # Verify decoded layout
        layout = vector["sig_structure_layout"]
        decoded = cbor2.loads(sig_structure)
        assert decoded[0] == layout["context"]  # "Signature1"
        assert decoded[1].hex() == layout["protected"]
        assert decoded[2] == b""  # external_aad
        assert decoded[3].hex() == layout["payload"]

    @pytest.mark.parametrize(
        "vector",
        [v for v in get_vectors() if "sig_structure_hash" in v],
        ids=lambda v: v["name"],
    )
    def test_sig_structure_hash(self, vector: dict[str, Any]) -> None:
        """SHA-256 hash of Sig_structure matches vector."""
        sig_structure = bytes.fromhex(vector["sig_structure"])
        sig_hash = hashlib.sha256(sig_structure).digest()
        assert sig_hash.hex() == vector["sig_structure_hash"]


class TestSignatureVerification:
    """Verify signatures against vectors using independent verifier."""

    @pytest.mark.parametrize(
        "vector",
        [
            v for v in get_vectors()
            if v.get("expected", {}).get("signature_valid", False)
            and "delegator_pubkey" in v  # Filter out partial vectors
        ],
        ids=lambda v: v["name"],
    )
    def test_signature_valid(self, vector: dict[str, Any]) -> None:
        """Valid signatures verify correctly."""
        pubkey = bytes.fromhex(vector["delegator_pubkey"])
        sig_hash = bytes.fromhex(vector["sig_structure_hash"])
        signature = bytes.fromhex(vector["signature"])

        assert verify(pubkey, sig_hash, signature), (
            f"Signature should be valid for {vector['name']}"
        )


class TestCoseSign1Decoding:
    """Test COSE_Sign1 decoding from vectors."""

    @pytest.mark.parametrize(
        "vector",
        [
            v for v in get_vectors()
            if v.get("coverage") == "delegation_token_cose_sign1"
            and v.get("expected", {}).get("scope_bits_valid", True)  # Exclude invalid scope
        ],
        ids=lambda v: v["name"],
    )
    def test_decode_cose_sign1(self, vector: dict[str, Any]) -> None:
        """COSE_Sign1 decodes correctly."""
        cose_bytes = bytes.fromhex(vector["cose_sign1"])
        token = DelegationToken.from_cose_sign1(cose_bytes)

        assert token.delegator_iid.hex() == vector["delegator_iid"]
        assert token.signature.hex() == vector["signature"]
        assert token.payload.delegate.hex() == vector["delegate_iid"]
        assert token.payload.scope == vector["scope"]
        assert token.payload.resource == vector["resource"]
        assert token.payload.expiry == vector["expiry"]
        assert token.payload.seq == vector["seq"]

    @pytest.mark.parametrize(
        "vector",
        [
            v for v in get_vectors()
            if v.get("coverage") == "delegation_token_cose_sign1"
            and v.get("expected", {}).get("scope_bits_valid", True)  # Exclude invalid scope
        ],
        ids=lambda v: v["name"],
    )
    def test_roundtrip(self, vector: dict[str, Any]) -> None:
        """COSE_Sign1 encode/decode roundtrip."""
        cose_bytes = bytes.fromhex(vector["cose_sign1"])
        token = DelegationToken.from_cose_sign1(cose_bytes)
        reencoded = token.to_cose_sign1()

        # Decode the reencoded version
        token2 = DelegationToken.from_cose_sign1(reencoded)
        assert token2.delegator_iid == token.delegator_iid
        assert token2.payload.delegate == token.payload.delegate
        assert token2.payload.scope == token.payload.scope
        assert token2.payload.resource == token.payload.resource
        assert token2.payload.expiry == token.payload.expiry
        assert token2.payload.seq == token.payload.seq

    def test_invalid_scope_rejected_on_decode(self) -> None:
        """Tokens with invalid scope bits are rejected during decode."""
        vector = get_vector("delegation_invalid_scope_bits")
        cose_bytes = bytes.fromhex(vector["cose_sign1"])

        with pytest.raises(ValueError, match="Invalid scope bits"):
            DelegationToken.from_cose_sign1(cose_bytes)


class TestScopeBitsValidation:
    """Test scope bit validation using vectors."""

    def test_invalid_scope_bits(self) -> None:
        """Reserved scope bits should fail validation."""
        vector = get_vector("delegation_invalid_scope_bits")
        expected = vector["expected"]

        # Signature should still be valid
        assert expected["signature_valid"] is True
        # But scope validation should fail
        assert expected["scope_bits_valid"] is False

        # Verify implementation rejects reserved bits
        with pytest.raises(ValueError, match="Invalid scope bits"):
            DelegationTokenPayload(
                delegate=bytes.fromhex(vector["delegate_iid"]),
                scope=vector["scope"],  # 0xFF has reserved bits set
                resource=vector["resource"],
                expiry=vector["expiry"],
                seq=vector["seq"],
            )


class TestDelegateMismatch:
    """Test delegate IID mismatch detection."""

    def test_delegate_mismatch(self) -> None:
        """Exercising node differs from token's delegate."""
        vector = get_vector("delegation_delegate_mismatch")
        expected = vector["expected"]

        # Signature is valid
        assert expected["signature_valid"] is True
        # But delegate does not match
        assert expected["delegate_match"] is False
        assert expected["overall_valid"] is False

        # The token itself is structurally valid
        cose_bytes = bytes.fromhex(vector["cose_sign1"])
        token = DelegationToken.from_cose_sign1(cose_bytes)

        # Verify the delegate in token differs from exercising node
        assert token.payload.delegate.hex() == vector["token_delegate_iid"]
        assert vector["token_delegate_iid"] != vector["exercising_iid"]


class TestAdminScopeRestrictions:
    """Test admin scope restriction vectors."""

    def test_admin_exceeds_scope(self) -> None:
        """Admin attempting to delegate owner-only capabilities."""
        vector = get_vector("delegation_admin_exceeds_scope")
        expected = vector["expected"]

        # Signature is valid
        assert expected["signature_valid"] is True
        # Scope bits are valid (within 0-4)
        assert expected["scope_bits_valid"] is True
        # But admin cannot delegate this scope
        assert expected["admin_delegation_valid"] is False
        # Owner could delegate it
        assert expected["owner_delegation_valid"] is True

        # Verify owner-only bits are present
        scope = vector["scope"]
        assert scope & DelegationScope.DISTRIBUTE_KEY
