#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project

import json
import re
import sys
from pathlib import Path


def c_ident(name):
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def hex_bytes(value):
    return bytes.fromhex(value)


def bytes_array(name, data):
    if data:
        values = ", ".join(f"0x{byte:02x}" for byte in data)
    else:
        values = "0"
    return f"static const uint8_t {name}[] = {{ {values} }};"


def parse_serial(encoded, name):
    if len(encoded) < 3:
        raise ValueError(f"{name} serial vector is truncated")
    payload_len = encoded[1] | (encoded[2] << 8)
    payload = encoded[3:]
    if len(payload) != payload_len:
        raise ValueError(f"{name} serial length mismatch")
    return encoded[0], payload


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_vectors.py INPUT_JSON OUTPUT_H")

    source = Path(sys.argv[1])
    out = Path(sys.argv[2])
    doc = json.loads(source.read_text())
    vectors = doc["vectors"]

    arrays = []
    rows = []
    error_rows = []

    for vector in vectors:
        name = vector["name"]
        kind = vector["frame"]
        encoded = hex_bytes(vector["encoded"])
        ident = c_ident(name)
        encoded_arr = f"v_{ident}_encoded"
        payload_arr = "NULL"
        payload_len = 0
        serial_marker = 0

        arrays.append(bytes_array(encoded_arr, encoded))
        if kind == "serial":
            serial_marker, payload = parse_serial(encoded, name)
            payload_arr = f"v_{ident}_serial_payload"
            payload_len = len(payload)
            arrays.append(bytes_array(payload_arr, payload))

        rows.append((
            name,
            f"MESHCORE_CODEC_VECTOR_{kind.upper()}",
            encoded_arr,
            len(encoded),
            payload_arr,
            payload_len,
            serial_marker,
        ))

        for response in vector.get("expect", {}).get("responses", []) or []:
            response_bytes = hex_bytes(response)
            if len(response_bytes) == 2 and response_bytes[0] == 0x01:
                resp_arr = f"v_{ident}_error_response"
                arrays.append(bytes_array(resp_arr, response_bytes))
                error_rows.append((name, response_bytes[1], resp_arr, len(response_bytes)))

    lines = [
        "/* Generated by lichen/tests/meshcore_codec/gen_vectors.py. */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "",
        "#ifndef LICHEN_TEST_MESHCORE_CODEC_VECTORS_H_",
        "#define LICHEN_TEST_MESHCORE_CODEC_VECTORS_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define MESHCORE_CODEC_VECTOR_SOURCE_COUNT {len(vectors)}U",
        f"#define MESHCORE_CODEC_VECTOR_COUNT {len(rows)}U",
        f"#define MESHCORE_CODEC_ERROR_VECTOR_COUNT {len(error_rows)}U",
        "",
        "enum meshcore_codec_vector_kind {",
        "\tMESHCORE_CODEC_VECTOR_COMMAND,",
        "\tMESHCORE_CODEC_VECTOR_PUSH,",
        "\tMESHCORE_CODEC_VECTOR_RESPONSE,",
        "\tMESHCORE_CODEC_VECTOR_SERIAL,",
        "};",
        "",
        "struct meshcore_codec_vector {",
        "\tconst char *name;",
        "\tenum meshcore_codec_vector_kind kind;",
        "\tconst uint8_t *encoded;",
        "\tsize_t encoded_len;",
        "\tconst uint8_t *serial_payload;",
        "\tsize_t serial_payload_len;",
        "\tuint8_t serial_marker;",
        "};",
        "",
        "struct meshcore_codec_error_vector {",
        "\tconst char *name;",
        "\tuint8_t error_code;",
        "\tconst uint8_t *encoded;",
        "\tsize_t encoded_len;",
        "};",
        "",
    ]
    lines.extend(arrays)
    lines.extend(["", "static const struct meshcore_codec_vector meshcore_codec_vectors[] = {"])
    for row in rows:
        name, kind, encoded_arr, encoded_len, payload_arr, payload_len, marker = row
        lines.append(
            f'\t{{ "{name}", {kind}, {encoded_arr}, {encoded_len}U, '
            f'{payload_arr}, {payload_len}U, 0x{marker:02x}U }},'
        )
    lines.extend(["};", "", "static const struct meshcore_codec_error_vector "
                  "meshcore_codec_error_vectors[] = {"])
    for name, error_code, resp_arr, resp_len in error_rows:
        lines.append(
            f'\t{{ "{name}", 0x{error_code:02x}U, {resp_arr}, {resp_len}U }},'
        )
    lines.extend(["};", "", "#endif /* LICHEN_TEST_MESHCORE_CODEC_VECTORS_H_ */", ""])
    out.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
