/* SPDX-License-Identifier: GPL-3.0-or-later */
/* SPDX-FileCopyrightText: The contributors to the LICHEN project */

#ifndef LICHEN_MESHCORE_CODEC_H_
#define LICHEN_MESHCORE_CODEC_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <lichen/meshcore/limits.h>

#define LICHEN_MESHCORE_SOURCE_MESHCORE_COMMIT \
	"e8d3c53ba1ea863937081cd0caad759b832f3028"
#define LICHEN_MESHCORE_APP_PROTOCOL_VERSION 3U
#define LICHEN_MESHCORE_SERIAL_APP_TO_DEVICE 0x3cU
#define LICHEN_MESHCORE_SERIAL_DEVICE_TO_APP 0x3eU

enum lichen_meshcore_command_id {
	LICHEN_MESHCORE_CMD_APP_START = 0x01,
	LICHEN_MESHCORE_CMD_SEND_TXT_MSG = 0x02,
	LICHEN_MESHCORE_CMD_SEND_CHANNEL_TXT_MSG = 0x03,
	LICHEN_MESHCORE_CMD_GET_CONTACTS = 0x04,
	LICHEN_MESHCORE_CMD_GET_DEVICE_TIME = 0x05,
	LICHEN_MESHCORE_CMD_SET_DEVICE_TIME = 0x06,
	LICHEN_MESHCORE_CMD_SEND_SELF_ADVERT = 0x07,
	LICHEN_MESHCORE_CMD_SET_ADVERT_NAME = 0x08,
	LICHEN_MESHCORE_CMD_ADD_UPDATE_CONTACT = 0x09,
	LICHEN_MESHCORE_CMD_SYNC_NEXT_MESSAGE = 0x0a,
	LICHEN_MESHCORE_CMD_SET_RADIO_PARAMS = 0x0b,
	LICHEN_MESHCORE_CMD_SET_RADIO_TX_POWER = 0x0c,
	LICHEN_MESHCORE_CMD_RESET_PATH = 0x0d,
	LICHEN_MESHCORE_CMD_SET_ADVERT_LATLON = 0x0e,
	LICHEN_MESHCORE_CMD_REMOVE_CONTACT = 0x0f,
	LICHEN_MESHCORE_CMD_SHARE_CONTACT = 0x10,
	LICHEN_MESHCORE_CMD_EXPORT_CONTACT = 0x11,
	LICHEN_MESHCORE_CMD_IMPORT_CONTACT = 0x12,
	LICHEN_MESHCORE_CMD_REBOOT = 0x13,
	LICHEN_MESHCORE_CMD_GET_BATT_AND_STORAGE = 0x14,
	LICHEN_MESHCORE_CMD_SET_TUNING_PARAMS = 0x15,
	LICHEN_MESHCORE_CMD_DEVICE_QUERY = 0x16,
	LICHEN_MESHCORE_CMD_EXPORT_PRIVATE_KEY = 0x17,
	LICHEN_MESHCORE_CMD_IMPORT_PRIVATE_KEY = 0x18,
	LICHEN_MESHCORE_CMD_SEND_RAW_DATA = 0x19,
	LICHEN_MESHCORE_CMD_SEND_LOGIN = 0x1a,
	LICHEN_MESHCORE_CMD_SEND_STATUS_REQ = 0x1b,
	LICHEN_MESHCORE_CMD_HAS_CONNECTION = 0x1c,
	LICHEN_MESHCORE_CMD_LOGOUT = 0x1d,
	LICHEN_MESHCORE_CMD_GET_CONTACT_BY_IDX = 0x1e,
	LICHEN_MESHCORE_CMD_GET_CHANNEL = 0x1f,
	LICHEN_MESHCORE_CMD_SET_CHANNEL = 0x20,
	LICHEN_MESHCORE_CMD_SIGN_START = 0x21,
	LICHEN_MESHCORE_CMD_SIGN_DATA = 0x22,
	LICHEN_MESHCORE_CMD_SIGN_FINISH = 0x23,
	LICHEN_MESHCORE_CMD_SEND_TRACE_PATH = 0x24,
	LICHEN_MESHCORE_CMD_SET_DEVICE_PIN = 0x25,
	LICHEN_MESHCORE_CMD_SET_OTHER_PARAMS = 0x26,
	LICHEN_MESHCORE_CMD_SEND_TELEMETRY = 0x27,
	LICHEN_MESHCORE_CMD_GET_CUSTOM_VARS = 0x28,
	LICHEN_MESHCORE_CMD_SET_CUSTOM_VAR = 0x29,
	LICHEN_MESHCORE_CMD_GET_ADVERT_PATH = 0x2a,
	LICHEN_MESHCORE_CMD_GET_TUNING_PARAMS = 0x2b,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_0 = 0x2c,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_1 = 0x2d,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_2 = 0x2e,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_3 = 0x2f,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_4 = 0x30,
	LICHEN_MESHCORE_CMD_RESERVED_WIFI_5 = 0x31,
	LICHEN_MESHCORE_CMD_SEND_BINARY_REQ = 0x32,
	LICHEN_MESHCORE_CMD_FACTORY_RESET = 0x33,
	LICHEN_MESHCORE_CMD_SEND_PATH_DISCOVERY = 0x34,
	LICHEN_MESHCORE_CMD_UNASSIGNED_35 = 0x35,
	LICHEN_MESHCORE_CMD_SET_FLOOD_SCOPE = 0x36,
	LICHEN_MESHCORE_CMD_SEND_CONTROL_REQ = 0x37,
	LICHEN_MESHCORE_CMD_GET_STATS = 0x38,
	LICHEN_MESHCORE_CMD_SEND_ANON_REQ = 0x39,
	LICHEN_MESHCORE_CMD_SET_AUTOADD_CONFIG = 0x3a,
	LICHEN_MESHCORE_CMD_GET_AUTOADD_CONFIG = 0x3b,
	LICHEN_MESHCORE_CMD_GET_ALLOWED_REPEAT_FREQ = 0x3c,
	LICHEN_MESHCORE_CMD_SET_PATH_HASH = 0x3d,
	LICHEN_MESHCORE_CMD_SEND_CHANNEL_DATA = 0x3e,
	LICHEN_MESHCORE_CMD_SET_DEFAULT_FLOOD_SCOPE = 0x3f,
	LICHEN_MESHCORE_CMD_GET_DEFAULT_FLOOD_SCOPE = 0x40,
	LICHEN_MESHCORE_CMD_SEND_RAW_PACKET = 0x41,
};

enum lichen_meshcore_response_id {
	LICHEN_MESHCORE_RESP_OK = 0x00,
	LICHEN_MESHCORE_RESP_ERR = 0x01,
	LICHEN_MESHCORE_RESP_CONTACTS_START = 0x02,
	LICHEN_MESHCORE_RESP_CONTACT = 0x03,
	LICHEN_MESHCORE_RESP_END_OF_CONTACTS = 0x04,
	LICHEN_MESHCORE_RESP_SELF_INFO = 0x05,
	LICHEN_MESHCORE_RESP_SENT = 0x06,
	LICHEN_MESHCORE_RESP_CURR_TIME = 0x09,
	LICHEN_MESHCORE_RESP_NO_MORE_MESSAGES = 0x0a,
	LICHEN_MESHCORE_RESP_BATT_AND_STORAGE = 0x0c,
	LICHEN_MESHCORE_RESP_DEVICE_INFO = 0x0d,
	LICHEN_MESHCORE_RESP_DISABLED = 0x0f,
	LICHEN_MESHCORE_RESP_CHANNEL_INFO = 0x12,
	LICHEN_MESHCORE_RESP_CUSTOM_VARS = 0x15,
	LICHEN_MESHCORE_RESP_AUTOADD_CONFIG = 0x19,
	LICHEN_MESHCORE_RESP_DEFAULT_FLOOD_SCOPE = 0x1c,
};

enum lichen_meshcore_error_code {
	LICHEN_MESHCORE_ERR_UNSUPPORTED_CMD = 1,
	LICHEN_MESHCORE_ERR_NOT_FOUND = 2,
	LICHEN_MESHCORE_ERR_TABLE_FULL = 3,
	LICHEN_MESHCORE_ERR_BAD_STATE = 4,
	LICHEN_MESHCORE_ERR_FILE_IO = 5,
	LICHEN_MESHCORE_ERR_ILLEGAL_ARG = 6,
};

struct lichen_meshcore_frame_view {
	uint8_t type;
	const uint8_t *payload;
	size_t payload_len;
};

int lichen_meshcore_decode_frame(const uint8_t *frame, size_t len,
				 struct lichen_meshcore_frame_view *view);
bool lichen_meshcore_command_known(uint8_t cmd);

int lichen_meshcore_encode_error(uint8_t err, uint8_t *out, size_t out_len);
int lichen_meshcore_encode_ok(uint8_t *out, size_t out_len);
int lichen_meshcore_encode_serial_frame(uint8_t marker, const uint8_t *payload,
					size_t payload_len, uint8_t *out,
					size_t out_len);

#endif /* LICHEN_MESHCORE_CODEC_H_ */
