# Heltec LoRa32 v3 board config — USB CDC-ACM + SLIP
# ESP32-S3 uses Zephyr's USB device stack next (UDC)

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_ESP32SX=y
CONFIG_USBD_CDC_ACM_CLASS=y

CONFIG_SLIP=y
CONFIG_NET_L2_SLIP=y
CONFIG_UART_LINE_CTRL=y
CONFIG_NET_BUF_DATA_SIZE=128
