#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Generate the Zephyr fixture header from tofu_edge_cases.json."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "test" / "vectors" / "tofu_edge_cases.json"
TARGET = ROOT / "lichen" / "tests" / "coap_keys" / "src" / "tofu_edge_vectors.h"


def _bytes(value: str) -> str:
    raw = bytes.fromhex(value)
    return ", ".join(f"0x{byte:02x}" for byte in raw)


def render() -> str:
    document = json.loads(SOURCE.read_bytes())
    by_name = {vector["name"]: vector for vector in document["vectors"]}
    first = by_name["first_contact"]
    independent = by_name["independent_peer"]
    return f"""/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Generated by test/vectors/generate_tofu_c_header.py; do not edit. */
#ifndef LICHEN_TEST_TOFU_EDGE_VECTORS_H_
#define LICHEN_TEST_TOFU_EDGE_VECTORS_H_

#define TOFU_EDGE_VECTOR_COUNT {len(document["vectors"])}U
#define TOFU_EDGE_ALICE_PUBKEY_BYTES {_bytes(first["pubkey_hex"])}
#define TOFU_EDGE_ALICE_IID_BYTES {_bytes(first["iid_hex"])}
#define TOFU_EDGE_BOB_PUBKEY_BYTES {_bytes(independent["pubkey_hex"])}
#define TOFU_EDGE_BOB_IID_BYTES {_bytes(independent["iid_hex"])}
#define TOFU_EDGE_CONCURRENT_OBSERVERS {by_name["concurrent_first_contact"]["concurrent_observers"]}U
#define TOFU_EDGE_REPLAY_REPETITIONS {by_name["replayed_collision"]["repetitions"]}U
#define TOFU_EDGE_FIRST_CONTACT_ENTRIES {first["expected"]["entry_count"]}U
#define TOFU_EDGE_INDEPENDENT_ENTRIES {independent["expected"]["entry_count"]}U

#endif /* LICHEN_TEST_TOFU_EDGE_VECTORS_H_ */
"""


def main() -> None:
    TARGET.write_text(render())


if __name__ == "__main__":
    main()
