/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: The contributors to the LICHEN project
 */

#include <zephyr/ztest.h>

#include <lichen/hal.h>

ZTEST(build_epoch, test_build_epoch_metadata)
{
	struct lichen_hal_time_snapshot snapshot;

	zassert_equal((uint32_t)CONFIG_LICHEN_TIME_BUILD_EPOCH_UNIX,
		      (uint32_t)LICHEN_BUILD_EPOCH_EXPECTED_EPOCH);

#if defined(LICHEN_BUILD_EPOCH_EXPECT_SOURCE_SOURCE_DATE_EPOCH)
	zassert_true(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DATE_EPOCH));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_RELEASE));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_GENERATED));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_FIXED));
#elif defined(LICHEN_BUILD_EPOCH_EXPECT_SOURCE_RELEASE)
	zassert_true(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_RELEASE));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DATE_EPOCH));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_GENERATED));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_FIXED));
#elif defined(LICHEN_BUILD_EPOCH_EXPECT_SOURCE_DEVELOPER_GENERATED)
	zassert_true(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_GENERATED));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DATE_EPOCH));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_RELEASE));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_FIXED));
	zassert_true(LICHEN_BUILD_EPOCH_DEVELOPER_GENERATED_CHECKED);
#elif defined(LICHEN_BUILD_EPOCH_EXPECT_SOURCE_DEVELOPER_FIXED)
	zassert_true(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_FIXED));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DATE_EPOCH));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_RELEASE));
	zassert_false(IS_ENABLED(CONFIG_LICHEN_TIME_BUILD_EPOCH_SOURCE_DEVELOPER_GENERATED));
	zassert_false(LICHEN_BUILD_EPOCH_DEVELOPER_GENERATED_CHECKED);
#else
#error "Missing build epoch source expectation"
#endif

	zassert_ok(lichen_hal_time_snapshot_get(&snapshot));
	zassert_equal(snapshot.build_epoch,
		      (uint32_t)LICHEN_BUILD_EPOCH_EXPECTED_EPOCH);
	zassert_equal(snapshot.effective_epoch_floor,
		      (uint32_t)LICHEN_BUILD_EPOCH_EXPECTED_EPOCH);
}

ZTEST_SUITE(build_epoch, NULL, NULL, NULL, NULL, NULL);
