manifest:
  version: "0.13"

  self:
    path: zephyr

  defaults:
    remote:
      name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v3.7.0
      import: true
