//! SCHC rule model (RFC 8724 §7).

use lichen_core::constants::{
    RULE_GLOBAL_COAP, RULE_GLOBAL_OSCORE, RULE_ICMPV6_ECHO, RULE_LINK_LOCAL_COAP,
    RULE_LINK_LOCAL_OSCORE, RULE_MQTT_SN, RULE_RPL_DAO, RULE_RPL_DIO, RULE_UNCOMPRESSED,
};

/// Matching Operator — decides whether a rule applies to a field value.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum Mo {
    Equal,
    #[default]
    Ignore,
    Msb,
    MatchMapping,
}

/// Compression/Decompression Action — what appears in the residue.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum Cda {
    #[default]
    NotSent,
    ValueSent,
    Lsb,
    Compute,
    MappingSent,
}

/// One field's compression behaviour within a rule (RFC 8724 §7.4).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct FieldDescriptor {
    /// Stable identifier, e.g. `"CoAP.MID"`.
    pub field_id: &'static str,
    /// Field width in bits.
    pub length_bits: u16,
    pub mo: Mo,
    pub cda: Cda,
    /// Target value for Equal/MSB matching and NotSent reconstruction.
    pub target_value: u128,
    /// For MSB: number of most-significant bits to match; also determines
    /// residue width (`length_bits - mo_arg`).
    pub mo_arg: Option<u16>,
}

/// A SCHC rule: an ordered list of field descriptors keyed by a rule ID.
///
/// Rule IDs 0-127 are compression rules; 255 is the uncompressed fallback.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rule {
    pub rule_id: u8,
    pub fields: &'static [FieldDescriptor],
}

// ---------------------------------------------------------------------------
// Whole-packet rule registry populated from Python rules.py (LINK_LOCAL_COAP_RULE etc)
// and codec.rs behavior. Matches appendix-schc.md and 03-adaptation.md tables.
// DAO base fields (kd_flags + reserved + seq + dodagid) now fully synced with Python rules.py:280 and Rust codec (lines 148-166 updated).
// ---------------------------------------------------------------------------

const LINK_LOCAL_PREFIX: u128 = 0xfe80u128 << 112;

pub const LINK_LOCAL_COAP_RULE: Rule = Rule {
    rule_id: RULE_LINK_LOCAL_COAP,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.traffic_class",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.flow_label",
            length_bits: 20,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.payload_length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 17,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.hop_limit",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.src",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "IPv6.dst",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "UDP.src_port",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.dst_port",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.checksum",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.version",
            length_bits: 2,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 1,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.type",
            length_bits: 2,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.tkl",
            length_bits: 4,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.code",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.mid",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
    ],
};
pub const GLOBAL_COAP_RULE: Rule = Rule {
    rule_id: RULE_GLOBAL_COAP,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.traffic_class",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.flow_label",
            length_bits: 20,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.payload_length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 17,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.hop_limit",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.src",
            length_bits: 128,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.dst",
            length_bits: 128,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.src_port",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.dst_port",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.checksum",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.version",
            length_bits: 2,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 1,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.type",
            length_bits: 2,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.tkl",
            length_bits: 4,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.code",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "CoAP.mid",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
    ],
};
pub const ICMPV6_ECHO_RULE: Rule = Rule {
    rule_id: RULE_ICMPV6_ECHO,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.traffic_class",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.flow_label",
            length_bits: 20,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.payload_length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 58,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.hop_limit",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.src",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "IPv6.dst",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "ICMPv6.type",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.code",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.checksum",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.identifier",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.sequence",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
    ],
};
pub const RPL_DIO_RULE: Rule = Rule {
    rule_id: RULE_RPL_DIO,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.traffic_class",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.flow_label",
            length_bits: 20,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.payload_length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 58,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.hop_limit",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.src",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "IPv6.dst",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "ICMPv6.type",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 155,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.code",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 1,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.checksum",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.instance",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.version",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.rank",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.gmop",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.dtsn",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.flags",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.reserved",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.dodagid",
            length_bits: 128,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
    ],
};
pub const RPL_DAO_RULE: Rule = Rule {
    rule_id: RULE_RPL_DAO,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.traffic_class",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.flow_label",
            length_bits: 20,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.payload_length",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 58,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.hop_limit",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.src",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "IPv6.dst",
            length_bits: 128,
            mo: Mo::Msb,
            cda: Cda::Lsb,
            target_value: LINK_LOCAL_PREFIX,
            mo_arg: Some(64),
        },
        FieldDescriptor {
            field_id: "ICMPv6.type",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 155,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.code",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 2,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "ICMPv6.checksum",
            length_bits: 16,
            mo: Mo::Ignore,
            cda: Cda::Compute,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.instance",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.kd_flags",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.reserved",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.seq",
            length_bits: 8,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "RPL.dodagid",
            length_bits: 128,
            mo: Mo::Ignore,
            cda: Cda::ValueSent,
            target_value: 0,
            mo_arg: None,
        },
    ],
};

pub const LINK_LOCAL_OSCORE_RULE: Rule = Rule {
    rule_id: RULE_LINK_LOCAL_OSCORE,
    fields: LINK_LOCAL_COAP_RULE.fields,
};
pub const GLOBAL_OSCORE_RULE: Rule = Rule {
    rule_id: RULE_GLOBAL_OSCORE,
    fields: GLOBAL_COAP_RULE.fields,
};
pub const MQTT_SN_RULE: Rule = Rule {
    rule_id: RULE_MQTT_SN,
    fields: &[
        FieldDescriptor {
            field_id: "IPv6.version",
            length_bits: 4,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 6,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "IPv6.next_header",
            length_bits: 8,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 17,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.src_port",
            length_bits: 16,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 10883,
            mo_arg: None,
        },
        FieldDescriptor {
            field_id: "UDP.dst_port",
            length_bits: 16,
            mo: Mo::Equal,
            cda: Cda::NotSent,
            target_value: 10883,
            mo_arg: None,
        },
    ],
};
pub const UNCOMPRESSED_RULE: Rule = Rule {
    rule_id: RULE_UNCOMPRESSED,
    fields: &[],
};
