#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Generate the C vector fixture for check-in/roll-call tests.

Reads the canonical oracle test/vectors/checkin_rollcall.json and emits a
header with wire bytes, expected decode outcomes, CoAP response codes, and
expected re-encodings. The JSON cbor_hex bytes are the sole wire oracle; the
cbor_length fields in the source file are stale (several disagree with the
hex) and are intentionally NOT consumed. Expected re-encodings are computed
with cbor2 (the Python oracle) after applying the documented decode
transforms (roll-call integer id is coerced to its decimal string form).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import cbor2


def classify(name: str, payload: dict[str, Any]) -> str:
    """Vector kind from the oracle's own vector-name prefix.

    Payload keys cannot discriminate reliably: an error vector whose payload
    is missing 'id' (the discriminator) looks like a check-in payload.
    """
    if name.startswith("rollcall_status"):
        return "rollcall_status"
    if name.startswith("rollcall"):
        return "rollcall_req"
    return "checkin"


def reencode_transform(kind: str, payload: dict[str, Any]) -> bytes:
    """Canonical bytes expected after decode->encode under documented transforms."""
    normalized = dict(payload)
    if kind == "rollcall_req" and isinstance(normalized.get("id"), int):
        normalized["id"] = str(normalized["id"])
    return cbor2.dumps(normalized)


def response_code_byte(expected: dict[str, Any]) -> int | None:
    code = expected.get("response_code")
    if code is None:
        return None
    cls, _, detail = code.partition(".")
    detail = detail.split(" ", 1)[0]
    return (int(cls) << 5) | int(detail)


def c_header_bytes(name: str, wire: bytes, indent: str = "  ") -> list[str]:
    lines = [f"{indent}static const uint8_t {name}[] = {{"]
    for offset in range(0, len(wire), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in wire[offset : offset + 16])
        lines.append(f"{indent}  {chunk},")
    lines.append(f"{indent}}};")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vectors-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    source = args.vectors_dir / "checkin_rollcall.json"
    with source.open(encoding="utf-8") as handle:
        document = json.load(handle)

    # Constants checks against the generator's own reading of the file.
    constants: dict[str, Any] = {}
    for vector in document["vectors"]:
        if "max_checkins" in vector:
            constants["max_checkins"] = vector["max_checkins"]
            constants["prune_policy"] = vector["expected"]["prune_policy"]
        if "max_rollcalls" in vector:
            constants["max_rollcalls"] = vector["max_rollcalls"]
            constants["max_timeout_s"] = vector["max_timeout_s"]
            constants["default_timeout_s"] = vector["default_timeout_s"]
        if "lat_range" in vector:
            constants["lat_min"] = vector["lat_range"]["min"]
            constants["lat_max"] = vector["lat_range"]["max"]
            constants["lon_min"] = vector["lon_range"]["min"]
            constants["lon_max"] = vector["lon_range"]["max"]
        if "valid_node_examples" in vector:
            constants["valid_nodes"] = vector["valid_node_examples"]
            constants["invalid_nodes"] = vector["invalid_node_examples"]

    required = ("max_checkins", "max_rollcalls", "max_timeout_s",
                "default_timeout_s", "lat_min", "lat_max", "lon_min", "lon_max")
    missing = [key for key in required if key not in constants]
    if missing:
        raise ValueError(f"constants vectors incomplete, missing {missing}")

    lines: list[str] = [
        "/* Auto-generated by gen_vectors.py from test/vectors/checkin_rollcall.json.",
        " * Do not edit; regenerate instead. The cbor_hex bytes are the oracle.",
        " */",
        "#ifndef CHECKIN_VECTORS_H_",
        "#define CHECKIN_VECTORS_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct checkin_vector {",
        "  const char *name;",
        "  const char *kind;        /* checkin | rollcall_req | rollcall_status */",
        "  const uint8_t *wire;",
        "  size_t wire_len;",
        "  int decode_success;",
        "  uint8_t response_code;   /* CoAP code byte, 0 when unspecified */",
        "  const char *error;       /* expected error string, NULL when none */",
        "  const char *fields;      /* space-joined fields_present, NULL when none */",
        "  const char *status_value;/* expected.status_value, NULL when none */",
        "  int lat_negative;        /* 1 when expected.lat_negative, else 0 */",
        "  const uint8_t *reencode; /* expected decode->encode bytes */",
        "  size_t reencode_len;",
        "};",
        "",
    ]

    vectors: list[dict[str, Any]] = []
    for index, vector in enumerate(document["vectors"]):
        name = vector["name"]
        wire_hex = vector.get("cbor_hex")
        if wire_hex is None:
            continue
        wire = bytes.fromhex(wire_hex)
        expected = vector.get("expected", {})
        payload = vector.get("cbor_payload")
        kind = "constant"
        reencode = wire
        if payload is not None:
            kind = classify(name, payload)
            reencode = reencode_transform(kind, payload)
            if expected.get("decode_success") and reencode != wire:
                # Only the documented id coercion may change bytes.
                if kind != "rollcall_req" or not isinstance(payload.get("id"), int):
                    raise ValueError(f"{name}: unexpected re-encode drift")
        else:
            reencode = wire

        wire_sym = f"wire_{index}"
        reenc_sym = f"reencode_{index}"
        lines.extend(c_header_bytes(wire_sym, wire))
        if reencode != wire:
            lines.extend(c_header_bytes(reenc_sym, reencode))
        else:
            lines.extend([f"  #define reencode_{index} wire_{index}"])
        lines.append("")

        fields = expected.get("fields_present")
        vectors.append({
            "sym": f"vectors[{len(vectors)}]",
            "name": name,
            "kind": kind,
            "wire_sym": wire_sym,
            "wire_len": len(wire),
            "decode_success": 1 if expected.get("decode_success") else 0,
            "response_code": response_code_byte(expected),
            "error": expected.get("error"),
            "fields": " ".join(fields) if fields else None,
            "status_value": expected.get("status_value"),
            "lat_negative": 1 if expected.get("lat_negative") is True else 0,
            "reencode_sym": reenc_sym,
            "reencode_len": len(reencode),
            "has_reencode": reencode != wire,
        })

    lines.append("static const struct checkin_vector vectors[] = {")
    for item in vectors:
        fields = f'"{item["fields"]}"' if item["fields"] else "NULL"
        error = f'"{item["error"]}"' if item["error"] else "NULL"
        status = f'"{item["status_value"]}"' if item["status_value"] else "NULL"
        code = item["response_code"] if item["response_code"] is not None else 0
        lines.append("  {")
        lines.append(f'    .name = "{item["name"]}",')
        lines.append(f'    .kind = "{item["kind"]}",')
        lines.append(f"    .wire = {item['wire_sym']},")
        lines.append(f"    .wire_len = {item['wire_len']},")
        lines.append(f"    .decode_success = {item['decode_success']},")
        lines.append(f"    .response_code = 0x{code:02x},")
        lines.append(f"    .error = {error},")
        lines.append(f"    .fields = {fields},")
        lines.append(f"    .status_value = {status},")
        lines.append(f"    .lat_negative = {item['lat_negative']},")
        lines.append(f"    .reencode = {item['reencode_sym']},")
        lines.append(f"    .reencode_len = {item['reencode_len']},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append(f"#define VECTORS_COUNT {len(vectors)}")
    lines.append("")

    def cstr(value: str | None) -> str:
        return f'"{value}"' if value is not None else "NULL"

    lines.append("struct checkin_constants {")
    lines.append("  size_t max_checkins;")
    lines.append("  size_t max_rollcalls;")
    lines.append("  uint32_t max_timeout_s;")
    lines.append("  uint32_t default_timeout_s;")
    lines.append("  double lat_min, lat_max, lon_min, lon_max;")
    lines.append("  const char *prune_policy;")
    lines.append("  const char *const *valid_nodes;")
    lines.append("  size_t valid_nodes_count;")
    lines.append("  const char *const *invalid_nodes;")
    lines.append("  size_t invalid_nodes_count;")
    lines.append("};")
    lines.append("")
    for label, key in (("valid", "valid_nodes"), ("invalid", "invalid_nodes")):
        entries = constants.get(key, [])
        lines.append(f"static const char *const {label}_node_examples[] = {{")
        for entry in entries:
            lines.append(f'  "{entry}",')
        lines.append("};")
    lines.append("")
    lines.append("static const struct checkin_constants constants = {")
    lines.append(f"  .max_checkins = {constants['max_checkins']},")
    lines.append(f"  .max_rollcalls = {constants['max_rollcalls']},")
    lines.append(f"  .max_timeout_s = {constants['max_timeout_s']},")
    lines.append(f"  .default_timeout_s = {constants['default_timeout_s']},")
    lines.append(f"  .lat_min = {constants['lat_min']!r},")
    lines.append(f"  .lat_max = {constants['lat_max']!r},")
    lines.append(f"  .lon_min = {constants['lon_min']!r},")
    lines.append(f"  .lon_max = {constants['lon_max']!r},")
    lines.append(f"  .prune_policy = {cstr(constants.get('prune_policy'))},")
    lines.append("  .valid_nodes = valid_node_examples,")
    lines.append(f"  .valid_nodes_count = {len(constants.get('valid_nodes', []))},")
    lines.append("  .invalid_nodes = invalid_node_examples,")
    lines.append(f"  .invalid_nodes_count = {len(constants.get('invalid_nodes', []))},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* CHECKIN_VECTORS_H_ */")
    lines.append("")

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.output}: {len(vectors)} wire vectors")


if __name__ == "__main__":
    main()
