# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Shared client model for native LICHEN applications."""

from lichen.client.ble import (
    LICHEN_LCI_CAPABILITY_SLIP_IPV6,
    LICHEN_LCI_PROFILE,
    LICHEN_LCI_VERSION,
    NUS_LCI_PROFILE,
    BleDeviceCandidate,
    BleLciMetadata,
    BleLciProfile,
    BlePacketTransport,
    BleTransportError,
    discover_lci_devices,
    read_lci_metadata,
)
from lichen.client.ip_coap import (
    AiocoapResourceSubscription,
    AiocoapResourceTransport,
    CoapTransportError,
    IpCoapConfig,
)
from lichen.client.lci import (
    LciClient,
    LciClientError,
    MessageSubscription,
    RawRxSubscription,
    ResourceSubscription,
    ResourceTransport,
)
from lichen.client.model import (
    Capabilities,
    CoapResult,
    ConfigSnapshot,
    ConnectionPhase,
    DeliveryState,
    DeviceStatus,
    DutyCycleState,
    Identity,
    LocalRFStats,
    MessageDraft,
    MessageReceipt,
    MessageRecord,
    Neighbor,
    RadioConfig,
    RadioState,
    RawDiagnosticResult,
    RawDiagnosticState,
    RawRxEvent,
    RawRxStatus,
    ReceiptResult,
    ReceiptStatus,
    Route,
    SendResult,
    TxQueueState,
)
from lichen.client.packet_coap import (
    PacketCoapConfig,
    PacketCoapResourceTransport,
    PacketDatagramChannel,
)
from lichen.client.transport import PacketTransport

__all__ = [
    "Capabilities",
    "CoapResult",
    "ConfigSnapshot",
    "ConnectionPhase",
    "DeliveryState",
    "DeviceStatus",
    "DutyCycleState",
    "Identity",
    "LICHEN_LCI_CAPABILITY_SLIP_IPV6",
    "LICHEN_LCI_PROFILE",
    "LICHEN_LCI_VERSION",
    "LciClient",
    "LciClientError",
    "LocalRFStats",
    "MessageDraft",
    "MessageReceipt",
    "MessageRecord",
    "MessageSubscription",
    "NUS_LCI_PROFILE",
    "Neighbor",
    "PacketCoapConfig",
    "PacketCoapResourceTransport",
    "PacketDatagramChannel",
    "PacketTransport",
    "RadioConfig",
    "RadioState",
    "RawDiagnosticResult",
    "RawDiagnosticState",
    "RawRxEvent",
    "RawRxStatus",
    "RawRxSubscription",
    "ResourceSubscription",
    "ResourceTransport",
    "ReceiptResult",
    "ReceiptStatus",
    "Route",
    "SendResult",
    "TxQueueState",
    "BleDeviceCandidate",
    "BleLciMetadata",
    "BleLciProfile",
    "BlePacketTransport",
    "BleTransportError",
    "AiocoapResourceSubscription",
    "AiocoapResourceTransport",
    "CoapTransportError",
    "IpCoapConfig",
    "discover_lci_devices",
    "read_lci_metadata",
]
