# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Native LICHEN client TUI shell and shared widgets."""

from .app import NativeClientApp
from .client import build_connection_factory, build_messaging_client, main
from .formatting import (
    MAX_DIAG_ROWS,
    NODE_CONFIG_FIELDS,
    RADIO_CONFIG_FIELDS,
    SENSITIVE_FIELD_PARTS,
    clip,
    config_rows,
    diagnostics_rows,
    duty_cycle_bar,
    field_line,
    flatten_diagnostics,
    format_duration_ms,
    log_rows_from_payload,
    mesh_neighbor_rows,
    mesh_route_rows,
    message_line,
    message_preview,
    outbound_record,
    parse_config_value,
    radio_rows,
    raw_diagnostics_available,
    rf_health_rows,
    safe_display_value,
    safe_float,
    safe_int,
    status_line,
    status_rows,
)
from .models import (
    ConfigRow,
    ConfigState,
    ConnectionClientFactory,
    DashboardState,
    DiagnosticRow,
    DiagnosticsState,
    LinkMode,
    LogRow,
    LogsState,
    MeshState,
    MessagePreview,
    MessageSubscriptionLike,
    MessagingClient,
    MessagingState,
    RadioTuiState,
    RawRxSubscriptionLike,
    RFHealthState,
    ShellStatus,
    UiState,
)
from .widgets import (
    ActivePane,
    CommandBar,
    ConfigTable,
    DiagnosticsPanel,
    LogPanel,
    MessageList,
    MessagingPanel,
    ModeNav,
    NativeStatusBar,
)

__all__ = [
    # app
    "NativeClientApp",
    # client
    "build_connection_factory",
    "build_messaging_client",
    "main",
    # formatting
    "MAX_DIAG_ROWS",
    "NODE_CONFIG_FIELDS",
    "RADIO_CONFIG_FIELDS",
    "SENSITIVE_FIELD_PARTS",
    "clip",
    "config_rows",
    "diagnostics_rows",
    "duty_cycle_bar",
    "field_line",
    "flatten_diagnostics",
    "format_duration_ms",
    "log_rows_from_payload",
    "mesh_neighbor_rows",
    "mesh_route_rows",
    "message_line",
    "message_preview",
    "outbound_record",
    "parse_config_value",
    "radio_rows",
    "raw_diagnostics_available",
    "rf_health_rows",
    "safe_display_value",
    "safe_float",
    "safe_int",
    "status_line",
    "status_rows",
    # models
    "ConfigRow",
    "ConfigState",
    "ConnectionClientFactory",
    "DashboardState",
    "DiagnosticRow",
    "DiagnosticsState",
    "LinkMode",
    "LogRow",
    "LogsState",
    "MeshState",
    "MessagePreview",
    "MessageSubscriptionLike",
    "MessagingClient",
    "MessagingState",
    "RadioTuiState",
    "RawRxSubscriptionLike",
    "RFHealthState",
    "ShellStatus",
    "UiState",
    # widgets
    "ActivePane",
    "CommandBar",
    "ConfigTable",
    "DiagnosticsPanel",
    "LogPanel",
    "MessageList",
    "MessagingPanel",
    "ModeNav",
    "NativeStatusBar",
]
