// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Config {}
/// Nested message and enum types in `Config`.
pub mod config {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct DeviceConfig {}
    /// Nested message and enum types in `DeviceConfig`.
    pub mod device_config {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Role {
            Client = 0,
            ClientMute = 1,
            Router = 2,
            RouterClient = 3,
            Repeater = 4,
            Tracker = 5,
            Sensor = 6,
            Tak = 7,
            ClientHidden = 8,
            LostAndFound = 9,
            TakTracker = 10,
            RouterLate = 11,
            ClientBase = 12,
        }
        impl Role {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Client => "CLIENT",
                    Self::ClientMute => "CLIENT_MUTE",
                    Self::Router => "ROUTER",
                    Self::RouterClient => "ROUTER_CLIENT",
                    Self::Repeater => "REPEATER",
                    Self::Tracker => "TRACKER",
                    Self::Sensor => "SENSOR",
                    Self::Tak => "TAK",
                    Self::ClientHidden => "CLIENT_HIDDEN",
                    Self::LostAndFound => "LOST_AND_FOUND",
                    Self::TakTracker => "TAK_TRACKER",
                    Self::RouterLate => "ROUTER_LATE",
                    Self::ClientBase => "CLIENT_BASE",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "CLIENT" => Some(Self::Client),
                    "CLIENT_MUTE" => Some(Self::ClientMute),
                    "ROUTER" => Some(Self::Router),
                    "ROUTER_CLIENT" => Some(Self::RouterClient),
                    "REPEATER" => Some(Self::Repeater),
                    "TRACKER" => Some(Self::Tracker),
                    "SENSOR" => Some(Self::Sensor),
                    "TAK" => Some(Self::Tak),
                    "CLIENT_HIDDEN" => Some(Self::ClientHidden),
                    "LOST_AND_FOUND" => Some(Self::LostAndFound),
                    "TAK_TRACKER" => Some(Self::TakTracker),
                    "ROUTER_LATE" => Some(Self::RouterLate),
                    "CLIENT_BASE" => Some(Self::ClientBase),
                    _ => None,
                }
            }
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PortNum {
    UnknownApp = 0,
    TextMessageApp = 1,
    RemoteHardwareApp = 2,
    PositionApp = 3,
    NodeinfoApp = 4,
    RoutingApp = 5,
    AdminApp = 6,
    TextMessageCompressedApp = 7,
    WaypointApp = 8,
    AudioApp = 9,
    DetectionSensorApp = 10,
    AlertApp = 11,
    KeyVerificationApp = 12,
    RemoteShellApp = 13,
    ReplyApp = 32,
    IpTunnelApp = 33,
    PaxcounterApp = 34,
    StoreForwardPlusplusApp = 35,
    NodeStatusApp = 36,
    MeshBeaconApp = 37,
    SerialApp = 64,
    StoreForwardApp = 65,
    RangeTestApp = 66,
    TelemetryApp = 67,
    ZpsApp = 68,
    SimulatorApp = 69,
    TracerouteApp = 70,
    NeighborinfoApp = 71,
    AtakPlugin = 72,
    MapReportApp = 73,
    PowerstressApp = 74,
    LorawanBridge = 75,
    ReticulumTunnelApp = 76,
    CayenneApp = 77,
    AtakPluginV2 = 78,
    LoraOtaApp = 79,
    GroupalarmApp = 112,
    PrivateApp = 256,
    AtakForwarder = 257,
    Max = 511,
}
impl PortNum {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownApp => "UNKNOWN_APP",
            Self::TextMessageApp => "TEXT_MESSAGE_APP",
            Self::RemoteHardwareApp => "REMOTE_HARDWARE_APP",
            Self::PositionApp => "POSITION_APP",
            Self::NodeinfoApp => "NODEINFO_APP",
            Self::RoutingApp => "ROUTING_APP",
            Self::AdminApp => "ADMIN_APP",
            Self::TextMessageCompressedApp => "TEXT_MESSAGE_COMPRESSED_APP",
            Self::WaypointApp => "WAYPOINT_APP",
            Self::AudioApp => "AUDIO_APP",
            Self::DetectionSensorApp => "DETECTION_SENSOR_APP",
            Self::AlertApp => "ALERT_APP",
            Self::KeyVerificationApp => "KEY_VERIFICATION_APP",
            Self::RemoteShellApp => "REMOTE_SHELL_APP",
            Self::ReplyApp => "REPLY_APP",
            Self::IpTunnelApp => "IP_TUNNEL_APP",
            Self::PaxcounterApp => "PAXCOUNTER_APP",
            Self::StoreForwardPlusplusApp => "STORE_FORWARD_PLUSPLUS_APP",
            Self::NodeStatusApp => "NODE_STATUS_APP",
            Self::MeshBeaconApp => "MESH_BEACON_APP",
            Self::SerialApp => "SERIAL_APP",
            Self::StoreForwardApp => "STORE_FORWARD_APP",
            Self::RangeTestApp => "RANGE_TEST_APP",
            Self::TelemetryApp => "TELEMETRY_APP",
            Self::ZpsApp => "ZPS_APP",
            Self::SimulatorApp => "SIMULATOR_APP",
            Self::TracerouteApp => "TRACEROUTE_APP",
            Self::NeighborinfoApp => "NEIGHBORINFO_APP",
            Self::AtakPlugin => "ATAK_PLUGIN",
            Self::MapReportApp => "MAP_REPORT_APP",
            Self::PowerstressApp => "POWERSTRESS_APP",
            Self::LorawanBridge => "LORAWAN_BRIDGE",
            Self::ReticulumTunnelApp => "RETICULUM_TUNNEL_APP",
            Self::CayenneApp => "CAYENNE_APP",
            Self::AtakPluginV2 => "ATAK_PLUGIN_V2",
            Self::LoraOtaApp => "LORA_OTA_APP",
            Self::GroupalarmApp => "GROUPALARM_APP",
            Self::PrivateApp => "PRIVATE_APP",
            Self::AtakForwarder => "ATAK_FORWARDER",
            Self::Max => "MAX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_APP" => Some(Self::UnknownApp),
            "TEXT_MESSAGE_APP" => Some(Self::TextMessageApp),
            "REMOTE_HARDWARE_APP" => Some(Self::RemoteHardwareApp),
            "POSITION_APP" => Some(Self::PositionApp),
            "NODEINFO_APP" => Some(Self::NodeinfoApp),
            "ROUTING_APP" => Some(Self::RoutingApp),
            "ADMIN_APP" => Some(Self::AdminApp),
            "TEXT_MESSAGE_COMPRESSED_APP" => Some(Self::TextMessageCompressedApp),
            "WAYPOINT_APP" => Some(Self::WaypointApp),
            "AUDIO_APP" => Some(Self::AudioApp),
            "DETECTION_SENSOR_APP" => Some(Self::DetectionSensorApp),
            "ALERT_APP" => Some(Self::AlertApp),
            "KEY_VERIFICATION_APP" => Some(Self::KeyVerificationApp),
            "REMOTE_SHELL_APP" => Some(Self::RemoteShellApp),
            "REPLY_APP" => Some(Self::ReplyApp),
            "IP_TUNNEL_APP" => Some(Self::IpTunnelApp),
            "PAXCOUNTER_APP" => Some(Self::PaxcounterApp),
            "STORE_FORWARD_PLUSPLUS_APP" => Some(Self::StoreForwardPlusplusApp),
            "NODE_STATUS_APP" => Some(Self::NodeStatusApp),
            "MESH_BEACON_APP" => Some(Self::MeshBeaconApp),
            "SERIAL_APP" => Some(Self::SerialApp),
            "STORE_FORWARD_APP" => Some(Self::StoreForwardApp),
            "RANGE_TEST_APP" => Some(Self::RangeTestApp),
            "TELEMETRY_APP" => Some(Self::TelemetryApp),
            "ZPS_APP" => Some(Self::ZpsApp),
            "SIMULATOR_APP" => Some(Self::SimulatorApp),
            "TRACEROUTE_APP" => Some(Self::TracerouteApp),
            "NEIGHBORINFO_APP" => Some(Self::NeighborinfoApp),
            "ATAK_PLUGIN" => Some(Self::AtakPlugin),
            "MAP_REPORT_APP" => Some(Self::MapReportApp),
            "POWERSTRESS_APP" => Some(Self::PowerstressApp),
            "LORAWAN_BRIDGE" => Some(Self::LorawanBridge),
            "RETICULUM_TUNNEL_APP" => Some(Self::ReticulumTunnelApp),
            "CAYENNE_APP" => Some(Self::CayenneApp),
            "ATAK_PLUGIN_V2" => Some(Self::AtakPluginV2),
            "LORA_OTA_APP" => Some(Self::LoraOtaApp),
            "GROUPALARM_APP" => Some(Self::GroupalarmApp),
            "PRIVATE_APP" => Some(Self::PrivateApp),
            "ATAK_FORWARDER" => Some(Self::AtakForwarder),
            "MAX" => Some(Self::Max),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceMetrics {
    #[prost(uint32, optional, tag = "1")]
    pub battery_level: ::core::option::Option<u32>,
    #[prost(float, optional, tag = "2")]
    pub voltage: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "3")]
    pub channel_utilization: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "4")]
    pub air_util_tx: ::core::option::Option<f32>,
    #[prost(uint32, optional, tag = "5")]
    pub uptime_seconds: ::core::option::Option<u32>,
}
/// GPS Position
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(sfixed32, optional, tag = "1")]
    pub latitude_i: ::core::option::Option<i32>,
    #[prost(sfixed32, optional, tag = "2")]
    pub longitude_i: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub altitude: ::core::option::Option<i32>,
    #[prost(fixed32, tag = "4")]
    pub time: u32,
    #[prost(enumeration = "position::LocSource", tag = "5")]
    pub location_source: i32,
    #[prost(enumeration = "position::AltSource", tag = "6")]
    pub altitude_source: i32,
    #[prost(fixed32, tag = "7")]
    pub timestamp: u32,
    #[prost(int32, tag = "8")]
    pub timestamp_millis_adjust: i32,
    #[prost(sint32, optional, tag = "9")]
    pub altitude_hae: ::core::option::Option<i32>,
    #[prost(sint32, optional, tag = "10")]
    pub altitude_geoidal_separation: ::core::option::Option<i32>,
    #[prost(uint32, tag = "11")]
    pub pdop: u32,
    #[prost(uint32, tag = "12")]
    pub hdop: u32,
    #[prost(uint32, tag = "13")]
    pub vdop: u32,
    #[prost(uint32, tag = "14")]
    pub gps_accuracy: u32,
    #[prost(uint32, optional, tag = "15")]
    pub ground_speed: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "16")]
    pub ground_track: ::core::option::Option<u32>,
    #[prost(uint32, tag = "17")]
    pub fix_quality: u32,
    #[prost(uint32, tag = "18")]
    pub fix_type: u32,
    #[prost(uint32, tag = "19")]
    pub sats_in_view: u32,
    #[prost(uint32, tag = "20")]
    pub sensor_id: u32,
    #[prost(uint32, tag = "21")]
    pub next_update: u32,
    #[prost(uint32, tag = "22")]
    pub seq_number: u32,
    #[prost(uint32, tag = "23")]
    pub precision_bits: u32,
}
/// Nested message and enum types in `Position`.
pub mod position {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum LocSource {
        LocUnset = 0,
        LocManual = 1,
        LocInternal = 2,
        LocExternal = 3,
    }
    impl LocSource {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::LocUnset => "LOC_UNSET",
                Self::LocManual => "LOC_MANUAL",
                Self::LocInternal => "LOC_INTERNAL",
                Self::LocExternal => "LOC_EXTERNAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "LOC_UNSET" => Some(Self::LocUnset),
                "LOC_MANUAL" => Some(Self::LocManual),
                "LOC_INTERNAL" => Some(Self::LocInternal),
                "LOC_EXTERNAL" => Some(Self::LocExternal),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AltSource {
        AltUnset = 0,
        AltManual = 1,
        AltInternal = 2,
        AltExternal = 3,
        AltBarometric = 4,
    }
    impl AltSource {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::AltUnset => "ALT_UNSET",
                Self::AltManual => "ALT_MANUAL",
                Self::AltInternal => "ALT_INTERNAL",
                Self::AltExternal => "ALT_EXTERNAL",
                Self::AltBarometric => "ALT_BAROMETRIC",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ALT_UNSET" => Some(Self::AltUnset),
                "ALT_MANUAL" => Some(Self::AltManual),
                "ALT_INTERNAL" => Some(Self::AltInternal),
                "ALT_EXTERNAL" => Some(Self::AltExternal),
                "ALT_BAROMETRIC" => Some(Self::AltBarometric),
                _ => None,
            }
        }
    }
}
/// User identity
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub long_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub short_name: ::prost::alloc::string::String,
    #[deprecated]
    #[prost(bytes = "vec", tag = "4")]
    pub macaddr: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "HardwareModel", tag = "5")]
    pub hw_model: i32,
    #[prost(bool, tag = "6")]
    pub is_licensed: bool,
    #[prost(enumeration = "config::device_config::Role", tag = "7")]
    pub role: i32,
    #[prost(bytes = "vec", tag = "8")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, optional, tag = "9")]
    pub is_unmessagable: ::core::option::Option<bool>,
}
/// Data payload within a mesh packet
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Data {
    #[prost(enumeration = "PortNum", tag = "1")]
    pub portnum: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub want_response: bool,
    #[prost(fixed32, tag = "4")]
    pub dest: u32,
    #[prost(fixed32, tag = "5")]
    pub source: u32,
    #[prost(fixed32, tag = "6")]
    pub request_id: u32,
    #[prost(fixed32, tag = "7")]
    pub reply_id: u32,
    #[prost(fixed32, tag = "8")]
    pub emoji: u32,
    #[prost(uint32, optional, tag = "9")]
    pub bitfield: ::core::option::Option<u32>,
}
/// Full node information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeInfo {
    #[prost(uint32, tag = "1")]
    pub num: u32,
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<User>,
    #[prost(message, optional, tag = "3")]
    pub position: ::core::option::Option<Position>,
    #[prost(float, tag = "4")]
    pub snr: f32,
    #[prost(fixed32, tag = "5")]
    pub last_heard: u32,
    #[prost(message, optional, tag = "6")]
    pub device_metrics: ::core::option::Option<DeviceMetrics>,
    #[prost(uint32, tag = "7")]
    pub channel: u32,
    #[prost(bool, tag = "8")]
    pub via_mqtt: bool,
    #[prost(uint32, optional, tag = "9")]
    pub hops_away: ::core::option::Option<u32>,
    #[prost(bool, tag = "10")]
    pub is_favorite: bool,
    #[prost(bool, tag = "11")]
    pub is_ignored: bool,
    #[prost(bool, tag = "12")]
    pub is_key_manually_verified: bool,
    #[prost(bool, tag = "13")]
    pub is_muted: bool,
    #[prost(bool, tag = "14")]
    pub has_xeddsa_signed: bool,
}
/// Over-the-mesh packet envelope
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeshPacket {
    #[prost(fixed32, tag = "1")]
    pub from: u32,
    #[prost(fixed32, tag = "2")]
    pub to: u32,
    #[prost(uint32, tag = "3")]
    pub channel: u32,
    #[prost(fixed32, tag = "6")]
    pub id: u32,
    #[prost(fixed32, tag = "7")]
    pub rx_time: u32,
    #[prost(float, tag = "8")]
    pub rx_snr: f32,
    #[prost(uint32, tag = "9")]
    pub hop_limit: u32,
    #[prost(bool, tag = "10")]
    pub want_ack: bool,
    #[prost(enumeration = "mesh_packet::Priority", tag = "11")]
    pub priority: i32,
    #[prost(int32, tag = "12")]
    pub rx_rssi: i32,
    #[deprecated]
    #[prost(enumeration = "mesh_packet::Delayed", tag = "13")]
    pub delayed: i32,
    #[prost(bool, tag = "14")]
    pub via_mqtt: bool,
    #[prost(uint32, tag = "15")]
    pub hop_start: u32,
    #[prost(bytes = "vec", tag = "16")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "17")]
    pub pki_encrypted: bool,
    #[prost(uint32, tag = "18")]
    pub next_hop: u32,
    #[prost(uint32, tag = "19")]
    pub relay_node: u32,
    #[prost(oneof = "mesh_packet::PayloadVariant", tags = "4, 5")]
    pub payload_variant: ::core::option::Option<mesh_packet::PayloadVariant>,
}
/// Nested message and enum types in `MeshPacket`.
pub mod mesh_packet {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Priority {
        Unset = 0,
        Min = 1,
        Background = 10,
        Default = 64,
        Reliable = 70,
        Response = 80,
        High = 100,
        Alert = 110,
        Ack = 120,
        Max = 127,
    }
    impl Priority {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unset => "UNSET",
                Self::Min => "MIN",
                Self::Background => "BACKGROUND",
                Self::Default => "DEFAULT",
                Self::Reliable => "RELIABLE",
                Self::Response => "RESPONSE",
                Self::High => "HIGH",
                Self::Alert => "ALERT",
                Self::Ack => "ACK",
                Self::Max => "MAX",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSET" => Some(Self::Unset),
                "MIN" => Some(Self::Min),
                "BACKGROUND" => Some(Self::Background),
                "DEFAULT" => Some(Self::Default),
                "RELIABLE" => Some(Self::Reliable),
                "RESPONSE" => Some(Self::Response),
                "HIGH" => Some(Self::High),
                "ALERT" => Some(Self::Alert),
                "ACK" => Some(Self::Ack),
                "MAX" => Some(Self::Max),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Delayed {
        NoDelay = 0,
        Broadcast = 1,
        Direct = 2,
    }
    impl Delayed {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NoDelay => "NO_DELAY",
                Self::Broadcast => "DELAYED_BROADCAST",
                Self::Direct => "DELAYED_DIRECT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NO_DELAY" => Some(Self::NoDelay),
                "DELAYED_BROADCAST" => Some(Self::Broadcast),
                "DELAYED_DIRECT" => Some(Self::Direct),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum PayloadVariant {
        #[prost(message, tag = "4")]
        Decoded(super::Data),
        #[prost(bytes, tag = "5")]
        Encrypted(::prost::alloc::vec::Vec<u8>),
    }
}
/// Hardware model identifiers (subset)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HardwareModel {
    Unset = 0,
    TloraV2 = 1,
    TloraV1 = 2,
    Tbeam = 4,
    HeltecV20 = 5,
    TEcho = 7,
    Rak4631 = 9,
    HeltecV21 = 10,
    HeltecV1 = 11,
    LilygoTbeamS3Core = 12,
    Rak11200 = 13,
    NanoG1 = 14,
    StationG1 = 25,
    LoraRelayV1 = 32,
    Nrf52840Pca10059 = 40,
    HeltecV3 = 43,
    HeltecWslV3 = 44,
    RpiPico = 47,
    HeltecWirelessTracker = 48,
    HeltecWirelessPaper = 49,
    TDeck = 50,
    TWatchS3 = 51,
    Portduino = 37,
    AndroidSim = 38,
    PrivateHw = 255,
}
impl HardwareModel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "UNSET",
            Self::TloraV2 => "TLORA_V2",
            Self::TloraV1 => "TLORA_V1",
            Self::Tbeam => "TBEAM",
            Self::HeltecV20 => "HELTEC_V2_0",
            Self::TEcho => "T_ECHO",
            Self::Rak4631 => "RAK4631",
            Self::HeltecV21 => "HELTEC_V2_1",
            Self::HeltecV1 => "HELTEC_V1",
            Self::LilygoTbeamS3Core => "LILYGO_TBEAM_S3_CORE",
            Self::Rak11200 => "RAK11200",
            Self::NanoG1 => "NANO_G1",
            Self::StationG1 => "STATION_G1",
            Self::LoraRelayV1 => "LORA_RELAY_V1",
            Self::Nrf52840Pca10059 => "NRF52840_PCA10059",
            Self::HeltecV3 => "HELTEC_V3",
            Self::HeltecWslV3 => "HELTEC_WSL_V3",
            Self::RpiPico => "RPI_PICO",
            Self::HeltecWirelessTracker => "HELTEC_WIRELESS_TRACKER",
            Self::HeltecWirelessPaper => "HELTEC_WIRELESS_PAPER",
            Self::TDeck => "T_DECK",
            Self::TWatchS3 => "T_WATCH_S3",
            Self::Portduino => "PORTDUINO",
            Self::AndroidSim => "ANDROID_SIM",
            Self::PrivateHw => "PRIVATE_HW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSET" => Some(Self::Unset),
            "TLORA_V2" => Some(Self::TloraV2),
            "TLORA_V1" => Some(Self::TloraV1),
            "TBEAM" => Some(Self::Tbeam),
            "HELTEC_V2_0" => Some(Self::HeltecV20),
            "T_ECHO" => Some(Self::TEcho),
            "RAK4631" => Some(Self::Rak4631),
            "HELTEC_V2_1" => Some(Self::HeltecV21),
            "HELTEC_V1" => Some(Self::HeltecV1),
            "LILYGO_TBEAM_S3_CORE" => Some(Self::LilygoTbeamS3Core),
            "RAK11200" => Some(Self::Rak11200),
            "NANO_G1" => Some(Self::NanoG1),
            "STATION_G1" => Some(Self::StationG1),
            "LORA_RELAY_V1" => Some(Self::LoraRelayV1),
            "NRF52840_PCA10059" => Some(Self::Nrf52840Pca10059),
            "HELTEC_V3" => Some(Self::HeltecV3),
            "HELTEC_WSL_V3" => Some(Self::HeltecWslV3),
            "RPI_PICO" => Some(Self::RpiPico),
            "HELTEC_WIRELESS_TRACKER" => Some(Self::HeltecWirelessTracker),
            "HELTEC_WIRELESS_PAPER" => Some(Self::HeltecWirelessPaper),
            "T_DECK" => Some(Self::TDeck),
            "T_WATCH_S3" => Some(Self::TWatchS3),
            "PORTDUINO" => Some(Self::Portduino),
            "ANDROID_SIM" => Some(Self::AndroidSim),
            "PRIVATE_HW" => Some(Self::PrivateHw),
            _ => None,
        }
    }
}
