# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project
"""Timing oracles (spec 09-packets-timing.md §14).

Aggregates trickle, DAO timing, duty cycle, airtime, CSMA, time sync,
SFN/TDMA and data-traffic oracles for ergonomic import.
"""

from lichen.timing.airtime import airtime_ms, airtime_us, airtime_us_with_params  # noqa: F401
from lichen.timing.csma import (  # noqa: F401
    CSMA_BACKOFF_MAX,
    CSMA_BACKOFF_UNIT_MS,
    CSMA_CAD_TIMEOUT_SYMBOLS,
    CSMA_RETRY_LIMIT,
    CsmaState,
    cw_for_exponent,
)
from lichen.timing.dao import (  # noqa: F401
    DAO_INITIAL_DELAY_MAX_MS,
    DAO_INITIAL_DELAY_MIN_MS,
    DAO_REFRESH_S,
    DAO_RETRY_DELAYS_MS,
    dao_initial_delay,
    dao_retry_delay,
)
from lichen.timing.data_traffic import (  # noqa: F401
    HEARTBEAT_INTERVAL_S,
    TELEMETRY_INTERVAL_MAX_S,
    TELEMETRY_INTERVAL_MIN_S,
)
from lichen.timing.duty_cycle import (  # noqa: F401
    EU868_DUTY_CYCLE_PERCENT,
    EU868_MAX_PACKETS_PER_HOUR,
    REGIONAL_CONFIGS,
    US915_FCC_DWELL_TIME_MS,
    RegionalDutyCycleEnforcer,
    RegionalDutyCycleLimit,
    duty_cycle_usage_percent,
    get_regional_limit,
    max_packets_per_hour,
)
from lichen.timing.sfn import DesyncFSM, DesyncState, hash_32, sfn_delta, slot_for  # noqa: F401
from lichen.timing.time_sync import (  # noqa: F401
    DEFAULT_MAX_BACKWARD_STEP_S,
    DEFAULT_MAX_CORRECTION_RATE_PPM,
    DEFAULT_MAX_CUMULATIVE_FORWARD_CORRECTION_S,
    DEFAULT_MAX_FORWARD_STEP_S,
    DEFAULT_MAX_INITIAL_EPOCH_LEAD_S,
    DEFAULT_MAX_PROVISION_LEAD_S,
    DEFAULT_MAX_SAMPLE_AGE_S,
    DEFAULT_SOURCE_PRECEDENCE_POLICY,
    DIO_TIME_OPTION_LEN,
    DIO_TIME_OPTION_TOTAL,
    DIO_TIME_OPTION_TYPE,
    MAX_CORRECTION_RATE_PPM,
    STRATUM_SOURCE_CLASSES,
    SYSTEM_MONOTONIC_CLOCK,
    DioTimeOption,
    DioTimeVerifier,
    EpochFloorAuthority,
    EpochFloorResult,
    MonotonicClock,
    ProvisionClearedState,
    ProvisionEpochMetadata,
    ProvisionEpochStatus,
    ProvisionRecord,
    ProvisionRollbackState,
    ProvisionVerifier,
    ProvisionVirginState,
    SourceClass,
    SourcePrecedencePolicy,
    Stratum,
    StratumTracker,
    TimeAdmin,
    TimeEvidence,
    TimeProvider,
    TimeSample,
    TimeStatus,
    can_establish_sample,
    effective_epoch_floor,
    evaluate_epoch_floor,
)
from lichen.timing.trickle import (  # noqa: F401
    TRICKLE_IMAX_DOUBLINGS,
    TRICKLE_IMAX_EXACT_MS,
    TRICKLE_IMAX_MS,
    TRICKLE_IMIN_MS,
    TRICKLE_K,
    TrickleTimer,
)

__all__ = [
    "CSMA_BACKOFF_MAX",
    "CSMA_BACKOFF_UNIT_MS",
    "CSMA_CAD_TIMEOUT_SYMBOLS",
    "CSMA_RETRY_LIMIT",
    "CsmaState",
    "DAO_INITIAL_DELAY_MAX_MS",
    "DAO_INITIAL_DELAY_MIN_MS",
    "DAO_REFRESH_S",
    "DAO_RETRY_DELAYS_MS",
    "DEFAULT_MAX_BACKWARD_STEP_S",
    "DEFAULT_MAX_CORRECTION_RATE_PPM",
    "DEFAULT_MAX_CUMULATIVE_FORWARD_CORRECTION_S",
    "DEFAULT_MAX_FORWARD_STEP_S",
    "DEFAULT_MAX_INITIAL_EPOCH_LEAD_S",
    "DEFAULT_MAX_PROVISION_LEAD_S",
    "DEFAULT_MAX_SAMPLE_AGE_S",
    "DEFAULT_SOURCE_PRECEDENCE_POLICY",
    "DIO_TIME_OPTION_LEN",
    "DIO_TIME_OPTION_TOTAL",
    "DIO_TIME_OPTION_TYPE",
    "DioTimeVerifier",
    "DioTimeOption",
    "DesyncFSM",
    "DesyncState",
    "EpochFloorAuthority",
    "EpochFloorResult",
    "HEARTBEAT_INTERVAL_S",
    "MonotonicClock",
    "MAX_CORRECTION_RATE_PPM",
    "ProvisionClearedState",
    "ProvisionEpochMetadata",
    "ProvisionEpochStatus",
    "ProvisionRecord",
    "ProvisionRollbackState",
    "ProvisionVirginState",
    "ProvisionVerifier",
    "REGIONAL_CONFIGS",
    "RegionalDutyCycleEnforcer",
    "RegionalDutyCycleLimit",
    "SourceClass",
    "SourcePrecedencePolicy",
    "STRATUM_SOURCE_CLASSES",
    "Stratum",
    "StratumTracker",
    "SYSTEM_MONOTONIC_CLOCK",
    "TimeAdmin",
    "TELEMETRY_INTERVAL_MAX_S",
    "TELEMETRY_INTERVAL_MIN_S",
    "TRICKLE_IMAX_EXACT_MS",
    "TRICKLE_IMAX_DOUBLINGS",
    "TRICKLE_IMAX_MS",
    "TRICKLE_IMIN_MS",
    "TRICKLE_K",
    "TrickleTimer",
    "TimeSample",
    "TimeEvidence",
    "TimeProvider",
    "TimeStatus",
    "US915_FCC_DWELL_TIME_MS",
    "airtime_ms",
    "airtime_us",
    "airtime_us_with_params",
    "can_establish_sample",
    "cw_for_exponent",
    "dao_initial_delay",
    "dao_retry_delay",
    "duty_cycle_usage_percent",
    "effective_epoch_floor",
    "evaluate_epoch_floor",
    "hash_32",
    "get_regional_limit",
    "max_packets_per_hour",
    "sfn_delta",
    "slot_for",
]
