#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: The contributors to the LICHEN project

import json
import re
import sys
from pathlib import Path


def c_ident(name):
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def hex_bytes(value):
    return bytes.fromhex(value)


def bytes_array(name, data):
    if data:
        values = ", ".join(f"0x{byte:02x}" for byte in data)
    else:
        values = "0"
    return f"static const uint8_t {name}[] = {{ {values} }};"


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_vectors.py INPUT_JSON OUTPUT_H")

    source = Path(sys.argv[1])
    out = Path(sys.argv[2])
    doc = json.loads(source.read_text())

    arrays = []
    rows = []
    source_count = len(doc["vectors"])

    for vector in doc["vectors"]:
        expect = vector["expect"]
        responses = expect.get("responses")
        if not expect.get("adapter_test") or responses is None:
            continue
        if len(responses) > 2:
            raise ValueError(f"{vector['name']} has too many responses")

        ident = c_ident(vector["name"])
        request = hex_bytes(vector["encoded"])
        response0 = hex_bytes(responses[0])
        response1 = hex_bytes(responses[1]) if len(responses) == 2 else b""
        req_arr = f"v_{ident}_request"
        resp0_arr = f"v_{ident}_response0"
        resp1_arr = f"v_{ident}_response1"

        arrays.append(bytes_array(req_arr, request))
        arrays.append(bytes_array(resp0_arr, response0))
        if response1:
            arrays.append(bytes_array(resp1_arr, response1))
        rows.append((
            vector["name"],
            req_arr,
            len(request),
            resp0_arr,
            len(response0),
            resp1_arr if response1 else "NULL",
            len(response1),
            len(responses),
        ))

    lines = [
        "/* Generated by lichen/tests/meshcore_adapter/gen_vectors.py. */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "",
        "#ifndef LICHEN_TEST_MESHCORE_VECTORS_H_",
        "#define LICHEN_TEST_MESHCORE_VECTORS_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define MESHCORE_VECTOR_SOURCE_COUNT {source_count}U",
        f"#define MESHCORE_VECTOR_ADAPTER_COUNT {len(rows)}U",
        "",
        "struct meshcore_vector {",
        "\tconst char *name;",
        "\tconst uint8_t *request;",
        "\tsize_t request_len;",
        "\tconst uint8_t *response0;",
        "\tsize_t response0_len;",
        "\tconst uint8_t *response1;",
        "\tsize_t response1_len;",
        "\tsize_t response_count;",
        "};",
        "",
    ]
    lines.extend(arrays)
    lines.extend(["", "static const struct meshcore_vector meshcore_vectors[] = {"])
    for row in rows:
        name, req, req_len, resp0, resp0_len, resp1, resp1_len, response_count = row
        lines.append(
            f'\t{{ "{name}", {req}, {req_len}U, {resp0}, {resp0_len}U, '
            f'{resp1}, {resp1_len}U, {response_count}U }},'
        )
    lines.extend(["};", "", "#endif /* LICHEN_TEST_MESHCORE_VECTORS_H_ */", ""])
    out.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
