"""LICHEN IPv6 network layer.

Address handling (IID derivation, link-local/ULA/GUA construction) and IPv6
packet construction/parsing.
"""

from lichen.ipv6.addr import (
    GUA_NETWORK,
    LINK_LOCAL_NETWORK,
    ULA_NETWORK,
    AddrError,
    AddressManager,
    Identity,
    Scope,
    address_from_prefix,
    eui64_to_iid,
    mac48_to_eui64,
    make_gua,
    make_link_local,
    make_ula,
    short_addr_to_iid,
)
from lichen.ipv6.icmpv6 import (
    DestUnreachableCode,
    EchoReply,
    EchoRequest,
    Icmpv6Error,
    Icmpv6ErrorMessage,
    Icmpv6Message,
    Icmpv6Type,
    TimeExceededCode,
    handle_icmpv6,
    icmpv6_checksum,
    make_dest_unreachable,
    make_packet_too_big,
    make_time_exceeded,
)
from lichen.ipv6.packet import (
    HEADER_LENGTH,
    ExtensionHeader,
    IPv6Header,
    IPv6Packet,
    NextHeader,
    PacketError,
)
from lichen.ipv6.udp import (
    UDP_HEADER_LENGTH,
    UDP_NEXT_HEADER,
    UdpDatagram,
    UdpError,
    udp_checksum,
)

__all__ = [
    "GUA_NETWORK",
    "HEADER_LENGTH",
    "LINK_LOCAL_NETWORK",
    "ULA_NETWORK",
    "AddrError",
    "AddressManager",
    "DestUnreachableCode",
    "EchoReply",
    "EchoRequest",
    "ExtensionHeader",
    "IPv6Header",
    "IPv6Packet",
    "Icmpv6Error",
    "Icmpv6ErrorMessage",
    "Icmpv6Message",
    "Icmpv6Type",
    "Identity",
    "NextHeader",
    "PacketError",
    "Scope",
    "TimeExceededCode",
    "UDP_HEADER_LENGTH",
    "UDP_NEXT_HEADER",
    "UdpDatagram",
    "UdpError",
    "udp_checksum",
    "address_from_prefix",
    "eui64_to_iid",
    "handle_icmpv6",
    "icmpv6_checksum",
    "mac48_to_eui64",
    "make_dest_unreachable",
    "make_gua",
    "make_link_local",
    "make_packet_too_big",
    "make_time_exceeded",
    "make_ula",
    "short_addr_to_iid",
]
